services:
  node-api:
    container_name: sp-app
    ports:
      - "5000:5000"
    image: sp-server
    build: ./
    networks:
      - sp-network
networks:
  sp-network:
    name: sp-network
    driver: bridge